[build-system]
requires=["setuptools>=60","wheel","Cython==0.29.30","numpy"]
build-backend="setuptools.build_meta"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
